version: "3"

services:
  app:
    build: ./
    environment:
      - REACT_APP_API=https://naxia-dev.sevenone.online/api/v1/
      - REACT_APP_WS=wss://naxia-dev.sevenone.online/wsapi
    ports:
      - 8080:80
